// angular-badminton-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <h1>Welcome to {{title}}!</h1>

    <router-outlet />
  `,
  styles: [],
})
export class AppComponent {
  title = 'angular-badminton-app';
}

<link href="./AJB-Icon.svg" rel="icon" type="image/svg+xml"/>
<header class="svg-container">
  <img alt="Logo" src="./logo-SVG.svg">
</header>

<nav class="button-container">
  <button aria-label="Numbers" id="numbers">Numbers</button>
  <button aria-label="Payment" id="payment">Payment</button>
  <button aria-label="Admin" id="admin">Admin</button>
</nav>

// vue-badminton-app/src/App.vue
<template>
  <div>
    <link href="./AJB-Icon.svg" rel="icon" type="image/svg+xml"/>
    <header class="svg-container">
      <img alt="Logo" src="/logo-SVG.svg"/>
    </header>

    <nav class="button-container">
      <button aria-label="Numbers" @click="handleButtonClick('numbers')">Numbers</button>
      <button aria-label="Payment" @click="handleButtonClick('payment')">Payment</button>
      <button aria-label="Admin" @click="handleButtonClick('admin')">Admin</button>
    </nav>
  </div>
</template>
